language: elixir

cache:
  directories:
    - _build
    - deps

matrix:
  include:
    - otp_release: 21.0
      elixir: 1.7.2
   - otp_release: 22.0
      elixir: 1.8.2

before_install:
  - curl https://sh.rustup.rs -sSf | sh -s -- -y

install:
  - mix local.rebar --force
  - mix local.hex --force

sudo: true

before_script:
  - mix deps.get --only test

script:
  - source $HOME/.cargo/env
  - mix credo
  - mix format --check-formatted
  - mix test
