language: elixir

cache:
  directories:
    - _build
    - deps

matrix:
  include:
    - otp_release: 21.0
      elixir: 1.7.2

before_install:
  - curl https://static.rust-lang.org/rustup.sh | sh

install:
  - mix local.rebar --force
  - mix local.hex --force

sudo: required

before_script:
  - mix deps.get --only test

script:
  - mix credo
  - mix format --check-formatted
  - mix test
